✨ Handle vercel preview manually
marilari88/zod-playground pull request #63
Opened 2024-08-12 22:27 UTC by marilari88

2024-08-12 23:12 UTC, giacomocerquone commented
Closes #58

2024-08-13 11:34 UTC, davc0n requested changes

2024-08-13 11:34 UTC, davc0n commented on .github/workflows/tag.yml
> +        run: npx playwright install --with-deps
```suggestion
        run: npm run test:init
```

2024-08-13 11:34 UTC, davc0n commented on .github/workflows/tag.yml
> +        run: npx playwright test
```suggestion
        run: npm test
```

2024-08-13 14:29 UTC, merged